# Generated by Django 3.2.7 on 2021-10-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_demand_disccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='client_id',
            new_name='client',
        ),
    ]
