version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    volumes:
        - type: bind
          source: ./sneakerhead.sql
          target: /data/db
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'sneakerhead'
       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
       MYSQL_USER: 'sneakerhead'
       MYSQL_PASSWORD: 'projeto-darede'
    container_name: mysql_db
  web:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/sneakerhead
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db